### ISSUE TITLE
[Bug] [PHP] 8.2 support

### ISSUE THREAD

**Issue by remicollet** [apache/skywalking#9755]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

CLI (apache/skywalking-cli)

### What happened

```
error[E0425]: cannot find value `name_length` in this scope
   --> /dev/shm/BUILD/php82-php-pecl-skywalking-agent-0.1.0/mycargo/phper/src/ini.rs:255:9
    |
255 |         name_length,
    |         ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_zend_get_parameters_array_ex` in this scope
     --> /dev/shm/BUILD/php82-php-pecl-skywalking-agent-0.1.0/mycargo/phper/src/values.rs:135:13
      |
135   |               _zend_get_parameters_array_ex(num_args.try_into().unwrap(), arguments.as_mut_ptr());
      |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `zend_get_parameters_array_ex`
      |
     ::: /dev/shm/BUILD/php82-php-pecl-skywalking-agent-0.1.0/NTS/target/release/build/phper-sys-ddd865524bd4c63b/out/php_bindings.rs:35951:5
      |
35951 | /     pub fn zend_get_parameters_array_ex(param_count: u32, argument_array: *mut zval)
35952 | |         -> zend_result;
      | |______________________- similarly named function `zend_get_parameters_array_ex` defined here


```

### What you expected to happen

PHP 8.2 support

### How to reproduce

Build using PHP 8.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jmjoy** [comment]
This should be supported in [phper](https://github.com/phper-framework/phper), but, the PHP 8.2 haven't released stable now.

**Comment by remicollet** [comment]
So https://github.com/phper-framework/phper/issues/58
